name: Push Docker Image to Registries

on:
    workflow_call:

env:
    HUB_BASE: iterativodo
    GIT_BASE: ghcr.io/iterativo-git
    GCR_BASE: gcr.io/iterativo

jobs:
    push:
        name: Push Image to Multiple Registries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Generate Slug Variables
              uses: rlespinasse/github-slug-action@v4

            - name: Prepare Docker Metadata
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: |
                  ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
                  ${{ env.HUB_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
                  ${{ env.GCR_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v1
              with:
                image: tonistiigi/binfmt:latest
                platforms: all

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to Google Container Registry (GCR)
              uses: docker/login-action@v1
              with:
                registry: gcr.io
                username: _json_key
                password: ${{ secrets.GKE_SA_KEY }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                target: production
                platforms: |
                  linux/amd64
                  linux/arm64
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=registry,ref=${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache
                cache-to: type=registry,ref=${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache,mode=max
